Add projects for events
buggregator/app pull request #92
Opened 2022-07-29 19:28 UTC by js361014

2022-07-30 05:36 UTC, butschster commented
Hi, @js361014!
Could you provide some information about using projects in the PR description.

- How to use it with Ray
- SMTP
- Sentry
- Var dumper
- Inspector

2022-07-31 14:24 UTC, js361014 commented
> Hi, @js361014! Could you provide some information about using projects in the PR description.
> 
>     * How to use it with Ray
> 
>     * SMTP
> 
>     * Sentry
> 
>     * Var dumper
> 
>     * Inspector

I've provided some information.

2022-07-31 14:25 UTC, butschster commented
> I've provided some information.

Are you ready to review?

2022-07-31 15:52 UTC, js361014 commented
> > I've provided some information.
> 
> Are you ready to review?

Yes.

2022-07-31 17:55 UTC, butschster commented
> > > I've provided some information.
> > 
> > 
> > Are you ready to review?
> 
> Yes.

Could you pay attention on my comments above?

2022-07-31 17:55 UTC, butschster requested changes

2022-07-31 17:56 UTC, butschster commented on app/Modules/Inspector/Interfaces/Http/Controllers/StoreEventAction.php
> +        $project = $queryBus->ask(new FindProjectByName('default'));
for example INSPECTOR_URL=http://projectid@127.0.0.1:23517/inspector

2022-08-01 01:46 UTC, js361014 commented
Maybe can we provide non-default projects for Smtp/Inspector/Ray in a separete PR? I think it could require from me to spend more time on getting deeper into Smtp/Inspector/Ray. I would prefer to focus now on sentry module.

2022-08-01 06:11 UTC, butschster commented
> Maybe can we provide non-default projects for Smtp/Inspector/Ray in a separete PR? I think it could require from me to spend more time on getting deeper into Smtp/Inspector/Ray. I would prefer to focus now on sentry module.

Ok, it's not a problem! Thank you for the PR, I really appreciate your contribution!

2022-08-01 06:26 UTC, butschster requested changes
Could you please, fix Code style 
https://github.styleci.io/analyses/22ZbyZ?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2022-08-01 06:26 UTC, butschster commented on app/Application/Commands/FindAllProjects.php
> +    public function __construct()
Remove constructor

2022-08-01 06:29 UTC, butschster commented
There is a problem with tests also. It would be great if you fix them.

2022-08-01 17:50 UTC, js361014 commented
I've fixed code style and tests.

2022-08-01 17:59 UTC, butschster approved these changes

2022-08-01 17:59 UTC, merged